### ISSUE TITLE
Sends logs to email (like - Puffader)?

### ISSUE THREAD

**Issue by joker8989** [xp4xbox/Python-Backdoor#1]
i wanted to know if the "python-backdoor" sends the logs to email like Puffader.py after 1000 len for example? or it shows on the screen of the attacker?

**Comment by xp4xbox** [comment]
It has three options (start) (stop) (dump). When you dump, it shows the logs right on the screen,

**Comment by tehseensagar** [comment]
@xp4xbox  great project. It would be great , if there path for dumping keylogs to a path and send them to server after certain keystroke and also save screen shot like in ever10 sec and store them in folder and send them back to server. As puffader design it loose connection as well.

Regards

**Comment by xp4xbox** [comment]
This way is more simple, if you want to dump screenshot, you enter the command and you will retrieve it instantly. Similar to how all the other programs like this work.
