### ISSUE TITLE
Client.exe autostart 

### ISSUE THREAD

**Issue by MMhide0** [xp4xbox/Python-Backdoor#11]
How to make client.exe from joining right away to autostart in the registry

**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

**Comment by xp4xbox** [comment]
What do you mean?

**Comment by MigMag12** [comment]
after enabling client.exe I would like to automatically add to autostart

**Comment by xp4xbox** [comment]
I guess once I have time il implement this.

**Comment by xp4xbox** [comment]
#14
