### ISSUE TITLE
How do I use this.

### ISSUE THREAD

**Issue by AeonCaptain** [xp4xbox/Python-Backdoor#20]
**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

I need to use this on a computer, but no instructions are given as far as I can tell. Could you give an explanation of the commands you can use and what they do, how to access the computer and how to use each of the commands? Any help would be greatly appreciated!

**Comment by xp4xbox** [comment]
Have you followed the instructions to build the finished executable?

**Comment by AeonCaptain** [comment]
I followed the setup.py one. Do I need to do that on both computers? They are both windows.

**Comment by xp4xbox** [comment]
Then if you open up the `dist` folder you should see the client.exe. That is the file that needs to be run on the target computer. You don't need to do setup.py more than once.

After you run the client.exe on the target computer, you can run the server.py file on your own computer to accept the connection.

**Comment by AeonCaptain** [comment]
Thank you!
