### ISSUE TITLE
Server stuck on "Listening on port 3000"

### ISSUE THREAD

**Issue by glinskicwb1988** [xp4xbox/Python-Backdoor#21]
OS: Win 10 x64 pro
Commit/Build: 0c53c14

Several times you get stuck on an action and are forced to close the command line. When you try to run py server.oy again, you get stuck on "Listening on port 3000".

The backdoor only go working again when the victim restarts the machine.

Example: ran the server.py for the first time after the victim run the client.

Connects perfectly, so I send the "--a" command to make the program run on startup.

My server.py stops responding after that and I have to close the command line and open the server.py again, but know, you only see the "Listening on port 3000" and nothing more.

After several tries, I see this only happens SOME times.

**Comment by xp4xbox** [comment]
Its because the server is waiting for a response from the client.

**Comment by lilzec** [comment]
> Its because the server is waiting for a response from the client.

(OS Windows 10)
And how to I accept a the request without the victim clicking on the "client.exe"

**Comment by xp4xbox** [comment]
You cant
