### ISSUE TITLE
Cannot send zip file to the victim

### ISSUE THREAD

**Issue by glinskicwb1988** [xp4xbox/Python-Backdoor#23]
OS: Win 10 x64 pro
Commit/Build: 0c53c14

I can sucessfuly upload a little txt file. No problem here.

But when I try to upload a larger .zip/.exe (9mb) I get stuck on "Total bytes sent: 25840891"

The file is not uploaded and I get stuck on the command line of server.py

Everytime this happens, I can't connect to the victim anymore until him/her reboots the machine.

**Comment by xp4xbox** [comment]
It usually takes a while for larger file sizes. Either that or the data is getting lost while being sent.
