### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by 201901111** [xp4xbox/Python-Backdoor#24]
**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]
(https://user-images.githubusercontent.com/58638540/73090425-59f40100-3efe-11ea-913b-a2f605f15d1e.jpg)
I am already run the client.exe file on my another computer it is runnig also but i can't listen anything if i want to get connection with internet so what port i should want to use.

**Comment by 201901111** [comment]
Help

**Comment by xp4xbox** [comment]
Use the default port (port 3000). Make sure the right ip is used when setting the program up.
