### ISSUE TITLE
Object Oriented request?

### ISSUE THREAD

**Issue by Ridley-nelson17** [xp4xbox/Python-Backdoor#26]
Not really an issue, but I have been looking for a lot of object oriented python socket programs, yours matched my needs, it isn’t object oriented though. If you could go though and explain what each function does that would be enough for me.

**Comment by xp4xbox** [comment]
Python isn't really an object-oriented language but it would be super easy to make it.

**Comment by Ridley-nelson17** [comment]
What i really am looking for iss a server and client organized into python classes. Assuming that should be easy

**Comment by xp4xbox** [comment]
Yes that's super easy il do it when I get time

**Comment by Ridley-nelson17** [comment]
I don't mean to bug you, but is there a bear estimate on when you will get around to this?

**Comment by xp4xbox** [comment]
Not sure exactly.

**Comment by xp4xbox** [comment]
If you want to get started on it, feel free.

**Comment by xp4xbox** [comment]
I started working on it but it was getting really complicated and not my priority right now.

Maybe eventually I will redo this project in another language but the way I wrote it originally was extremely scripty and dirty and meant just to work.
