### ISSUE TITLE
Pyinstaller is missing a ton of modules

### ISSUE THREAD

**Issue by lilzec** [xp4xbox/Python-Backdoor#27]
**OS:** [Kali LInux]

The Backdoor doesn't work. Pyinstaller is missing a ton of top-level; modules.
any suggestions

**Comment by lilzec** [comment]
Fixed the last Issue. I just wanted to ask what happened to the webcam screenshots. if you have the code send so can add it in

**Comment by xp4xbox** [comment]
https://github.com/xp4xbox/Python-Backdoor/releases/tag/2

You can find the code here. I removed the feature because it increased the file size dramatically.
