### ISSUE TITLE
how 

### ISSUE THREAD

**Issue by overseer666** [xp4xbox/Python-Backdoor#29]
**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

**Comment by overseer666** [comment]
help?

**Comment by overseer666** [comment]
idk what im doing can someone help me learn this stuff

**Comment by overseer666** [comment]
or point me in the right direction i wanna learn to write.

**Comment by xp4xbox** [comment]
Just read the readme. It shows you how to setup the program.

**Comment by overseer666** [comment]
do i run setup.py with python? and if so how?

**Comment by overseer666** [comment]
it wont run from windows.

**Comment by overseer666** [comment]
im sorry im a noob...

**Comment by xp4xbox** [comment]
`python setup.py` in windows.

**Comment by overseer666** [comment]
im confused i type in the ip and the python window closes. am i doing something wrong? can you possibly make a video for noobs like me?

**Comment by overseer666** [comment]
having trouble at building to .exe

**Comment by xp4xbox** [comment]
run python setup.py in a cmd window it will show more detailed output.
