### ISSUE TITLE
Reenabling Task Manager

### ISSUE THREAD

**Issue by Y4hL** [xp4xbox/Python-Backdoor#30]
**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

Is there a way to reenable task manager, if not I would like that added.

**Comment by xp4xbox** [comment]
Re-enter the command to enable it. Or run `taskkill /f /im cscript.exe` in command prompt

**Comment by Y4hL** [comment]
One more thing, is the connection encrypted?

**Comment by xp4xbox** [comment]
Nope
