### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by f0lg0** [xp4xbox/Python-Backdoor#31]
Hope this is the right place where to ask.
How did you handle the cmd instance of the client? I can't test it since i don't have Windows right now and I was wondering if the user sees a cmd instance on the Desktop or it is completely hidden.
I am building a backdoor too and at the moment I found a workaround for this using vbs scripts ny hiding the backdoor.exe completely.
Thanks!

**Comment by xp4xbox** [comment]
The way I handled it was by creating a virtual cmd. So I used `subprocess.Popen` on the client-side to run the commands then sent the output back to the server.
