### ISSUE TITLE
Enhancement Suggestion to SetUp.py

### ISSUE THREAD

**Issue by JakeWnuk** [xp4xbox/Python-Backdoor#32]
**OS:** [Kali]

**Suggestion**: When using setup.py from a terminal you have to encapsulate every argument in string quotes for it to run without breaking. If you cast it as a string before using the argument you can avoid that and make it easier for end users who might not be Python natives.

**Example**: 

print("1. Use: " + strCurrentIP)
print("2. Use a different IP address for server")
print("3. Use a DNS Hostname")

strChoice = ""
strChoice = **str**(input("\n" + "Type selection: "))

if strChoice == "1":
    pass
...

**Comment by xp4xbox** [comment]
You cant run `setup.py` from terminal anyways it only builds on windows.

**Comment by JakeWnuk** [comment]
Tested on windows and no issue as seen above. closing issue.

**Comment by PawanKumarPandit** [comment]
I'm facing issue while sending and receiving files to client machine it stuck and won't execute any comment. After click ctrl + c. I lost my connection and again I can't able to establish a connection.  Plz help anyone if know.

**Comment by Y4hL** [comment]
@PawanKumarPandit What OS are you using and what is your Python version

**Comment by xp4xbox** [comment]
Please create a new issue, this isn't the right spot for it.
