### ISSUE TITLE
Failed to execute script client

### ISSUE THREAD

**Issue by Fizwizbiz** [xp4xbox/Python-Backdoor#33]
Hello ! 

I've downloaded this Python Backdoor on my VM Windows correctly, I disabled my firewall in my Ubuntu host (server side), I launch the server script, it's listening on port 4444 and then when I double-click on the exe in my VM Windows, I have this message "Failed to execute script client", with no explanation. I've tried to run it in cmd to see if there is an error message but no.. 

So I'm lost, I think I did it correctly. Thanks :)  

EDIT : I've tried to run just the client.py and I have an error message "no module named pyscreeze" but I've checked and the module is installed..

**Comment by xp4xbox** [comment]
What version of python are you using?
