### ISSUE TITLE
Can't merge int with str

### ISSUE THREAD

**Issue by Ismail099** [xp4xbox/Python-Backdoor#34]
Hello, great idea and nice code but I noticed that you are merging integers with strings in "list_connections" which is giving me an Error back (on server-side). Also, if I remove them (the numbers), that Line of Code is still giving me an IndexError as follows: 
  
   in list_connections     
   str(arrAddresses[intCounter][1]) + 4*" " + str(arrAddresses[intCounter][2]) + 4*" " + \
   IndexError: tuple index out of range

I'll be very grateful if you have any how to fix those? 

Thanks in advance
3301-byte

**Comment by xp4xbox** [comment]
Its not because of merging integers its something else.
