### ISSUE TITLE
client cannot reconnect after server crash

### ISSUE THREAD

**Issue by ittech25** [xp4xbox/Python-Backdoor#37]
client cannot reconnect after server crash

**Comment by xp4xbox** [comment]
in look into it.

**Comment by xp4xbox** [comment]
I think the real problem is the server crashing since even killing the process will still allow the client to reconnect. When does the server crash?

**Comment by ittech25** [comment]
Yes, Server crash when killing the process.
When server restart, client cannot reconnect

**Comment by xp4xbox** [comment]
try running both in a command window see what the output is.

**Comment by ittech25** [comment]
1 . I killed server ==> restart server => client connected ok
2. I try killed server again ==> restart server => alway stuck in Listening on port

I test on windows 10 and ngrok

**Comment by xp4xbox** [comment]
I tried killing it multiple times, the client still connects. Maybe try changing line 442 in client.py to `except:` instead of `except socket.error:`.

**Comment by ittech25** [comment]
Thank you @xp4xbox 
I change line 442 as you help
error as image below when i killed server and reopen 
Server
![image](https://user-images.githubusercontent.com/63135414/84452318-afe3fe00-ac7f-11ea-82dd-d9dbc4d854d4.png)
Client
![image](https://user-images.githubusercontent.com/63135414/84452436-018c8880-ac80-11ea-9e62-d997377088be.png)

**Comment by ittech25** [comment]
Test 2nd :

![image](https://user-images.githubusercontent.com/63135414/84452687-ae670580-ac80-11ea-8e97-ffacb012ca6b.png)

**Comment by xp4xbox** [comment]
Right below line 79 do you want to add `print(client_info)` so I can see what data that list has when you get that error?

**Comment by ittech25** [comment]
error does not appear as picture above
But killed the server and restart, it's stuck 
Connected
![image](https://user-images.githubusercontent.com/63135414/84459692-44575c00-ac92-11ea-9204-c0d2ede9f676.png)

Restart Server , stuck on Listening on port 3000, client not reconnect 

![image](https://user-images.githubusercontent.com/63135414/84459877-add76a80-ac92-11ea-9f2c-a4cba056d3da.png)

**Comment by ittech25** [comment]
Error appear
![image](https://user-images.githubusercontent.com/63135414/84460587-884b6080-ac94-11ea-8c35-d644b42ecea5.png)
![image](https://user-images.githubusercontent.com/63135414/84460688-ccd6fc00-ac94-11ea-9809-40ffaf468cce.png)

**Comment by xp4xbox** [comment]
Try changing line 154 in `refresh_connections()` from `except socket.error:` to just `except:`

**Comment by ittech25** [comment]
Error below
![image](https://user-images.githubusercontent.com/63135414/84555744-bc805900-ad48-11ea-8d2b-eaed439b036a.png)

**Comment by ittech25** [comment]
maybe error appear when i use ngrok ?
![image](https://user-images.githubusercontent.com/63135414/84556394-abd1e200-ad4c-11ea-8e35-07866bca696f.png)

**Comment by xp4xbox** [comment]
Whats ngrok

**Comment by ittech25** [comment]
Ngrok : expose local server to internet (https://ngrok.com/)
Because ISP in my country does not provide static ip

**Comment by xp4xbox** [comment]
Ah I think i know the problem do you want to add `print(strUserInfo)` to line 100 in client.py and show the output.

**Comment by Y4hL** [comment]
> Error appear
> 
> ![image](https://user-images.githubusercontent.com/63135414/84460688-ccd6fc00-ac94-11ea-9809-40ffaf468cce.png)
> 
> ![image](https://user-images.githubusercontent.com/63135414/84460897-4b339e00-ac95-11ea-8265-abddadd30c58.png)

I believe this error can be fixed with changing `del arrAddresses[intCounter]` to `arrAddresses.remove(conn)`. This should prevent index out of range errors

**Comment by ittech25** [comment]
Waiting result,
![image](https://user-images.githubusercontent.com/63135414/84556912-4b44a400-ad50-11ea-92a4-23e7bc792b86.png)

**Comment by xp4xbox** [comment]
part of the problem is that since you are using ngroc hostname socket.gethostname() returns nothing. so il have to fix that. 

did you try doing `arrAddresses.remove(conn)`?

**Comment by ittech25** [comment]
Yes, i tried

**Comment by Y4hL** [comment]
Ngrok port forwarding service, I don't think it interferes with socket.gethostname()

**Comment by ittech25** [comment]
![image](https://user-images.githubusercontent.com/63135414/84556973-269cfc00-ad51-11ea-8cf2-fbeee81a5d9e.png)

**Comment by xp4xbox** [comment]
try this instead ` del arrAddresses[arrConnections.index(conn)]
            arrConnections.remove(conn)`

**Comment by xp4xbox** [comment]
@Y4hL any reason why socket.gethostname returns blank then?

**Comment by Y4hL** [comment]
I think socket.gethostname() returns DESKTOP-XXXX

**Comment by xp4xbox** [comment]
oh wait yeah your right, platform.system() and platform.release() arent showing up

**Comment by Y4hL** [comment]
It think it would make it much easier if the list was sent in json format instead of splitting strings

**Comment by ittech25** [comment]
> try this instead ` del arrAddresses[arrConnections.index(conn)] arrConnections.remove(conn)` for thoses two lines.

Restart Server , stuck on Listening on port 3000
https://user-images.githubusercontent.com/63135414/84459877-add76a80-ac92-11ea-9f2c-a4cba056d3da.png

**Comment by Y4hL** [comment]
@xp4xbox I can make the client send the client_info in json format, but it would require an extra import, is that fine?

**Comment by xp4xbox** [comment]
That's fine

**Comment by Y4hL** [comment]
#38 @ittech25 try using ngrok with these changes

**Comment by ittech25** [comment]
Error accepting connections!
![image](https://user-images.githubusercontent.com/63135414/84562095-dedf9a00-ad7b-11ea-837a-28036d5e1a1c.png)

**Comment by ittech25** [comment]
No error appear. But i killed server and restart, client cannot reconnect.

**Comment by ittech25** [comment]
Hi @xp4xbox @Y4hL 
I tried using serveo (same ngrok) - expose local server to internet
Working fine. No error appear.
Thank you for your support ^^
