### ISSUE TITLE
Source Code Of The Backdoor?

### ISSUE THREAD

**Issue by VedantBhalgama** [xp4xbox/Python-Backdoor#40]
Hi!
Can I get the source code of the backdoor?

**Comment by VedantBhalgama** [comment]
And how can i implement a screenshot system like you in my backdoor which i have also created using python??

**Comment by xp4xbox** [comment]
The source is right here?

**Comment by xp4xbox** [comment]
The screenshot function was made using pyscreeze which was then sent over the the server. Check the source code.
