### ISSUE TITLE
Failed to execute script pyi_rth_pkgres - Error

### ISSUE THREAD

**Issue by Star-Shade-88** [xp4xbox/Python-Backdoor#45]
An error message pops up: Failed to execute script pyi_rth_pkgres
(in the client exe file)
please help

**Comment by xp4xbox** [comment]
Are you using the most updated commit? I didn't get any errors assuming you get the error when opening the client.exe file. Also what version of python are you using.

**Comment by Star-Shade-88** [comment]
I cloned the project and downloaded the zip file. 
I am using Python 3.7

**Comment by Star-Shade-88** [comment]
Probably the setup.py inputs matter?

**Comment by xp4xbox** [comment]
What were your inputs?

**Comment by Star-Shade-88** [comment]
A dns hostname, default port, add ro startup and all others not.

**Comment by xp4xbox** [comment]
Try going into setup.py and removing the `--windowed` on line 177 and run it in a command window to see the log.

**Comment by Star-Shade-88** [comment]
The error is:
![backdoorError](https://user-images.githubusercontent.com/52970344/86468112-08fef900-bd37-11ea-998b-8c89892a05b5.PNG)

**Comment by Y4hL** [comment]
Try the troubleshooting tips from this stackoverflow question: https://stackoverflow.com/questions/37815371/pyinstaller-failed-to-execute-script-pyi-rth-pkgres-and-missing-packages

**Comment by Star-Shade-88** [comment]
It worked!
Thanks

**Comment by Star-Shade-88** [comment]
Type

pip uninstall pyinstaller
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip

In console.


asdat3 <notifications@github.com> schrieb am Mi., 28. Okt. 2020, 00:02:

**Comment by asdat3** [comment]
Hey,
okayyy tried that already
didnt work for me :(
thanks anyways

**Comment by Star-Shade-88** [comment]
What's the problem?

asdat3 <notifications@github.com> schrieb am Mi., 28. Okt. 2020, 09:19:

**Comment by asdat3** [comment]
https://github.com/xp4xbox/Python-Backdoor/issues/49
@Star-Shade-88

**Comment by Star-Shade-88** [comment]
Did you run pip uninstall pyinstaller

asdat3 <notifications@github.com> schrieb am Mi., 28. Okt. 2020, 11:31:

**Comment by asdat3** [comment]
yes

**Comment by asdat3** [comment]
I reinstalled it with the zip then

**Comment by asdat3** [comment]
also downloaded the github pyinstaller thing and installed it via running the setup.py after downloading

**Comment by Star-Shade-88** [comment]
Type

pip uninstall pyinstaller
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip

In console.

And don't install with setup.py


asdat3 <notifications@github.com> schrieb am Mi., 28. Okt. 2020, 12:04:

**Comment by asdat3** [comment]
I did that already as I told you

**Comment by asdat3** [comment]
I did both

**Comment by Star-Shade-88** [comment]
Ok... I have no clue how.

asdat3 <notifications@github.com> schrieb am Mi., 28. Okt. 2020, 12:18:

**Comment by Y4hL** [comment]
Add a try except to all imports and then print out the full error, this way you can see which import is causing trouble

**Comment by asdat3** [comment]
ok yeah

**Comment by asdat3** [comment]
Is it possible that somebody else here compiles my exe please?
**port:** 3000 (default)
**ip:** 185.78.255.231
**melt into temp:** yes
**autostart:** yes
**UPX:** doesnt matter

would be awesome 👍
