### ISSUE TITLE
Download Multiple Files

### ISSUE THREAD

**Issue by asdat3** [xp4xbox/Python-Backdoor#50]
**OS:** e.g. Windows 10

Hey,
Is it possible to download multiple files from the client?
if yes, how?

Thanks

**Comment by Y4hL** [comment]
You could zip multiple files together and then transfer it.

**Comment by asdat3** [comment]
Is there a way to zip files?
I want the files **from** the client

**Comment by Y4hL** [comment]
A simple google search will give you your answer. Windows has a built in zip manager in powershell: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive
