### ISSUE TITLE
Error with pynput when using pyinstaller (client.exe)

### ISSUE THREAD

**Issue by TomasCartman** [xp4xbox/Python-Backdoor#51]
**OS:** Windows 10
**Commit/Build:** 8c76803

It seems that pynput doesn't allow send by other process on Windows. I can run the code normally using client.py, but when i try to use pyinstaller to build an .exe, the .exe do not start. Running pyinstaller with --debug=all, i get the following error when i try to run the client.exe:

File "C:\Users\{username}\AppData\Roaming\Python\Python38\site-packages\pynput\keyboard\__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "C:\Users\{username}\AppData\Roaming\Python\Python38\site-packages\pynput\_util\__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError

**Comment by ArlenRicard** [comment]
I'm having the same problem, when compiling and trying to open client.exe, I run into the following error, and the screen closes at the same moment.
However, if I run client.py, it works normally.
![error](https://user-images.githubusercontent.com/38087120/99812314-10c40c00-2b25-11eb-972f-80ce2614d43e.png)

**Comment by FeronFae** [comment]
Yeah, apparently in one of the newer versions of Pyinstall there's an issue with importing the modules required for it. I managed to fix the issue myself by adding two extra instructions in setup.py, more exactly in the lines **177** and **189**. I simply added the following expressions into both lines to fix the issue and stop the Executable from giving me a _Fatal Script Error_:

`--hidden-import pynput.keyboard._win32 --hidden-import pynput.mouse._win32`

I simply imported the pynput modules separately.
