### ISSUE TITLE
How to  add up automatically  client.exe file in registry (startup)

### ISSUE THREAD

**Issue by standalones1** [xp4xbox/Python-Backdoor#56]
Dear sir, this code is very useful. thank you for sharing this code, I need some help with how to add up the client.exe file in the registry without passing the command from the server i.e( --a run at startup)
.please guide me on how to modify this code automatically startup the client.exe file in the registry
 
I have a v2 python backdoor
 Thank you

**Comment by xp4xbox** [comment]
In the setup.py it allows you to add to startup automatically.
