### ISSUE TITLE
Giving an error while runing setup.py

### ISSUE THREAD

**Issue by Padmanabh82** [xp4xbox/Python-Backdoor#58]
**OS:** [Parrot OS]

while running setup.py i am getting an error and it is **(sh: 1: /usr/bin/Scripts/pyinstaller: not found)**.
only this is not a problem the modules are not getting installed. the error of pywin32 is **(ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none))and(ERROR: No matching distribution found for pywin32)**. wmi module is also giving same error.

**Comment by xp4xbox** [comment]
Try using an older version of python, looks like the modules havent been updated yet.

**Comment by Padmanabh82** [comment]
I am using Linux so I have 2.7, 3.8, 3.9 working together

**Comment by Padmanabh82** [comment]
You made backdoor over TCP protocol but what happens if it's over https it's more secure and fast protocol and antivirus will also not detect virus

**Comment by xp4xbox** [comment]
2.7 won't work , you need a windows PC to compile as in instructions. Http works for web based servers not p2p.

**Comment by Y4hL** [comment]
I think only the server is currently cross platform

**Comment by xp4xbox** [comment]
The server is cross platform, but the client is not, and you have to build the client on a windows pc.
