### ISSUE TITLE
Cant find Client.py 

### ISSUE THREAD

**Issue by wufflepuff** [xp4xbox/Python-Backdoor#60]
When i run setup.py it gives this error: 
**C:\Users\Sean\Desktop>python Python-Backdoor/src/setup.py
client.py not found!**

**Comment by xp4xbox** [comment]
you have to run it in the same directory as the setup.py file.

`cd Python-Backdoor/src/`
`python setup.py`

**Comment by xp4xbox** [comment]
Fixed 8c2bf2f
