### ISSUE TITLE
Cant Skip Icon

### ISSUE THREAD

**Issue by wufflepuff** [xp4xbox/Python-Backdoor#61]
**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

It says Press Enter to skip but when i press enter it cancel the setup.

**Comment by xp4xbox** [comment]
It's not canceling, something is wrong with Pyinstaller. Try running the setup in a PowerShell window or cmd. Right-click hold shift, open PowerShell window here, then type `python setup.py`. Tell show me the output where it cancels.

**Comment by wufflepuff** [comment]
![Bild_2021-03-21_220654](https://user-images.githubusercontent.com/80975776/111920873-be263c80-8a91-11eb-8251-421b3fdb9e30.png)
It says (in german): The system can not find the path specified.

**Comment by xp4xbox** [comment]
On line 5 add `print(python_path)`

**Comment by wufflepuff** [comment]
still the same

**Comment by wufflepuff** [comment]
wait here C:\Users\Sean\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0

**Comment by Hawkern** [comment]
👽👽👽👽👽👽👽👽👽👽👽👽👽👽👽👽

**Comment by xp4xbox** [comment]
The problem is it cant find your pyinstaller location, can you search for pyinstaller and see where the folder is on your computer?

@wufflepuff

**Comment by Rezureaxx** [comment]
Hey i have the same problem...

**Comment by xp4xbox** [comment]
@Rezureaxx can you find where your pyinstaller location is?

**Comment by xp4xbox** [comment]
3d814bf

**Comment by anqoVoube** [comment]
type----------
os.system("cd " + python_path)
    os.system("pyinstaller client.py " + strUPX + " --hidden-import pynput.keyboard._win32 --hidden-import pynput.mouse._win32 --exclude-module FixTk --exclude-module tcl --exclude-module tk "
                      "--exclude-module _tkinter --exclude-module tkinter --exclude-module Tkinter "
                      "--onefile --windowed --icon=\"" + strIconChoice + "\"")
instead of-----------
os.system(python_path + "\pyinstaller\" client.py " + strUPX + " --hidden-import pynput.keyboard._win32 --hidden-import pynput.mouse._win32 --exclude-module FixTk --exclude-module tcl --exclude-module tk "
                      "--exclude-module _tkinter --exclude-module tkinter --exclude-module Tkinter "
                      "--onefile --windowed")
line number 177
