### ISSUE TITLE
Pyinstaller path not found

### ISSUE THREAD

**Issue by Rezureaxx** [xp4xbox/Python-Backdoor#62]
Hey i am working on windows and i like the project but there is one issue with the setup.py file.
It can not find my pyinstaller.

I installed the requirements.
And I also downloaded the Pyinstaller.exe again.
Is there a pyinstaller.exe command i can run to build the exe?

Thanks :D

**Comment by xp4xbox** [comment]
What is your pyinstaller path?

**Comment by Rezureaxx** [comment]
I dont know....If i type pyinstaller in cmd i get the error that it can not find it...
But if i type pip install pyinstaller i get this : 

```
Requirement already satisfied: pyinstaller in c:\users\marvin\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (4.2)
Requirement already satisfied: pefile>=2017.8.1 in c:\users\marvin\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pyinstaller) (2019.4.18)
Requirement already satisfied: altgraph in c:\users\marvin\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pyinstaller) (0.17)
Requirement already satisfied: setuptools in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\site-packages (from pyinstaller) (49.2.1)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\users\marvin\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pyinstaller) (0.2.0)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in c:\users\marvin\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pyinstaller) (2021.1)
Requirement already satisfied: future in c:\users\marvin\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pefile>=2017.8.1->pyinstaller) (0.18.2)
```

**Comment by xp4xbox** [comment]
Open up your python install directory and search for 'pyinstaller'

**Comment by Rezureaxx** [comment]
c:\users\marvin\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (4.2)
This is my pyinstaller path

**Comment by xp4xbox** [comment]
And what is your python install path?

**Comment by haythemou** [comment]
simply uninstall python, re-install it and tick "Add Python to Path" at the installation graphical interface. Try it and let me know if it worked.

**Comment by Rezureaxx** [comment]
Okay i tried it a second time and now it works.
I uninstalled python and installed it again and added it to the path.
Then i installed all the requierements and now it works.

Good Work and thanks

**Comment by haythemou** [comment]
I'm glad it works ! Happy to help.
