### ISSUE TITLE
Bypass AV

### ISSUE THREAD

**Issue by Rezureaxx** [xp4xbox/Python-Backdoor#64]
Hello thanks for the great project.
However, I have a question.
Is it possible to bypass Windows Defender?
And no I don't want to use this program as BlackHat and I don't plan to in the future....
If you don't want to tell or don't know either it's no problem of course, then I will close this again.

Thanks

**Comment by xp4xbox** [comment]
I havent looked into it, maybe I will at some point, it might be triggered by something specific.

**Comment by gratisCobalt** [comment]
https://www.virustotal.com/gui/file/23fcdff87775db95896ac129250af01e7cc068b84ad6c9103dd7c00d693e813d/detection

hmmm.... shouldn't get detected by anything....

**Comment by xp4xbox** [comment]
Don't use virustotal, use something like nodistribute
