### ISSUE TITLE
if i want to make it connect every 5 sec to the server what i should do 

### ISSUE THREAD

**Issue by pretech86** [xp4xbox/Python-Backdoor#68]
**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

if i want to make it connect every 5 sec to the server what i should do

**Comment by xp4xbox** [comment]
The client already tries to connect every 5 seconds.

**Comment by pretech86** [comment]
but it not work with me , can you check  again please

**Comment by xp4xbox** [comment]
Double checked its working, the client tries to connect every 5 seconds until it gets a connection
