### ISSUE TITLE
error while transfer file 

### ISSUE THREAD

**Issue by pretech86** [xp4xbox/Python-Backdoor#70]
when i transfer file i get blanking and nothing happened , i used windows 10

**Comment by xp4xbox** [comment]
I tried it locally, it works, try using a smaller file, sending large data over TCP is volatile.

**Comment by gratisCobalt** [comment]
another thing I noticed... if you want to send a file (e.g. you are already accessing like the server.py) you do not get an error on server side but the client crashes and displays an error message
also if you "ctrl + c" out of the server console an error message is displayed, too

maybe you can catch these errors to prevent the client to crash in the first case and prevent displaying an error on client side?
