### ISSUE TITLE
sh: 1: /usr/bin/Scripts/pyinstaller: not found

### ISSUE THREAD

**Issue by rohanraj-aipro** [xp4xbox/Python-Backdoor#75]
python3 setup.py
1. Use: 192.168.0.104
2. Use a different IP address for server
3. Use a DNS Hostname
4. Use 127.0.0.1 (for testing on this computer)

Type selection: 4

Enter port number (Press ENTER for default):

Melt file on execution to tmp folder? y/n: y

Add program to startup on launch? y/n: n

Use UPX? y/n (Decreases file size but may not work on fresh computers): n

Path for icon (Press ENTER to skip):
sh: 1: /usr/bin/Scripts/pyinstaller: not found

**Comment by xp4xbox** [comment]
Did you make sure yo add python to path during installation

**Comment by Anarbb** [comment]
Up happened to me too, i do have python in my PATH i think it happens when you run the setup in a virtualenv

**Comment by Hacker-Rohan-Raj** [comment]
I executed it in Command Prompt:- Windows 11 OS

**Comment by Hacker-Rohan-Raj** [comment]
And New error:- 

1. Use: 192.168.0.101
2. Use a different IP address for server
3. Use a DNS Hostname
4. Use 127.0.0.1 (for testing on this computer)

Type selection: 4

Enter port number (Press ENTER for default):

Melt file on execution to tmp folder? y/n: y

Add program to startup on launch? y/n: n

Use UPX? y/n (Decreases file size but may not work on fresh computers): n

Path for icon (Press ENTER to skip):
The system cannot find the path specified.

(I Pressed Enter for Icon. Not Working !!!)

**Comment by xp4xbox** [comment]
where is your pyinstaller path do you know?

**Comment by Hacker-Rohan-Raj** [comment]
I dont know .

But i runt the program on my desktop. i am using windows 11. not windows 10.

**Comment by xp4xbox** [comment]
Will be fixed in new merge

**Comment by rohanraj-aipro** [comment]
ok
