### ISSUE TITLE
error building EXE windows10

### ISSUE THREAD

**Issue by skydyve** [xp4xbox/Python-Backdoor#76]
C:\Users\Admin\Desktop\Python-Backdoor-master\src>python setup.py
1. Use: 192.168.1.38
2. Use a different IP address for server
3. Use a DNS Hostname
4. Use 127.0.0.1 (for testing on this computer)

Type selection: 4

Enter port number (Press ENTER for default):

Melt file on execution to tmp folder? y/n: y

Add program to startup on launch? y/n: y

Use UPX? y/n (Decreases file size but may not work on fresh computers): n

Path for icon (Press ENTER to skip):
C: \ Program 'is not recognized as an internal command
or external, an executable program or a batch file.

i have this error

**Comment by xp4xbox** [comment]
Its something wrong with your path, make sure to add python to path.

**Comment by skydyve** [comment]
no i have the path...

**Comment by xp4xbox** [comment]
Where is your pyinstaller install directory

**Comment by skydyve** [comment]
is on this directory:
C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\Scripts\pyinstaller.py
