### ISSUE TITLE
Doesn't work on other PCs 

### ISSUE THREAD

**Issue by nacholmedina** [xp4xbox/Python-Backdoor#78]
When i build the server i add my to client.py like this 

After that i open no ip and select my hosy, check that the 3 checkmarks are green and working i add it on client.py in strHost
![image](https://user-images.githubusercontent.com/54557023/145515184-d9d6f02c-7da8-4560-aabb-30eea678669a.png)
And after i do that i run the setup.py in vscode 

1. Use: 192.168.0.200
2. Use a different IP address for server       
3. Use a DNS Hostname
4. Use 127.0.0.1 (for testing on this computer)

Type selection: 3

I add the exact hostname that i did in client.py 

Enter port number (Press ENTER for default): 3000

Melt file on execution to tmp folder? y/n: y

Add program to startup on launch? y/n: y

Use UPX? y/n (Decreases file size but may not work on fresh computers): n

it builds it without a single problem and it works perfectly on my Pc

however, when i try to execute on my friend's pc (wich has the same version of win10 as mine), i open the server on my PC, but it stays in "Listening on port 3000" forever and i never get the connection. 

Am i using the right ip? what should i do? 

IMPORTANT NOTE: When i use it on my pc i introduce my ipv4 in the client file. When i use this hostname it doesnt work on any pc, so i guess theres the problem, but i dont know wich ip should i introduce or what opction should i choose on setup

**Comment by 1Harrysmile** [comment]
is your friend PC on the same network with your PC?

**Comment by nacholmedina** [comment]
> is your friend PC on the same network with your PC?

No, It isnt

**Comment by 1Harrysmile** [comment]
try to connect the two pc on the same network and use your pc ip, and see if that will work.

**Comment by nacholmedina** [comment]
> try to connect the two pc on the same network and use your pc ip, and see if that will work.

I know. It obviously does. But thats nit what i want to do. I want to know how you use It on pcs that are on another Network

**Comment by xp4xbox** [comment]
check to make sure that port 3000 is open using your global IP

**Comment by xp4xbox** [comment]
The hostname above I tested on port 3000 and its closed

**Comment by nacholmedina** [comment]
I dont know what u mean by  making sure that port 3000 is open using my global IP. But ive already testes It on my pc with my IP and It works perfectly. And i Aldo dont know if this IS relevant for the test youve made but at that time my pc and no-ip were turned off

**Comment by xp4xbox** [comment]
when you are testing the backdoor, do a port scan on port 3000 on the hostname you are using.
