### ISSUE TITLE
I am facing this issue :(

### ISSUE THREAD

**Issue by studentnoo** [xp4xbox/Python-Backdoor#79]
ValueError: Fernet key must be 32 url-safe base64-encoded bytes

**Comment by xp4xbox** [comment]
When do you get this error.

**Comment by studentnoo** [comment]
> When do you get this error.

when i was using a tcp address :(

**Comment by studentnoo** [comment]
> When do you get this error.

bhuh when i an running it on localhost network it is fine but on WAN it is showing this :(

**Comment by xp4xbox** [comment]
when does the error appear though when running the program.

**Comment by studentnoo** [comment]
> when does the error appear though when running the program.

its problem with client :(

**Comment by xp4xbox** [comment]
when though, like when you open the program, when you connect, i need more details.

**Comment by xp4xbox** [comment]
you can drag and drop images through github coments

**Comment by studentnoo** [comment]
![Screenshot 2021-12-28 221634](https://user-images.githubusercontent.com/86470814/147588317-36774629-e4f9-41b6-8228-894a79806880.png)
<this is the error while running client :(

**Comment by xp4xbox** [comment]
The latest commit should fix it

**Comment by studentnoo** [comment]
> The latest commit should fix it

No its showing same error
 :(

**Comment by studentnoo** [comment]
Hey one thing if you use port number in four digits like 1234 it works but when you use service like ngrok it's not working because you by default get 5 digit port number.


I though maybe this could help you a bit.
:)

**Comment by studentnoo** [comment]
> The latest commit should fix it

Hey

**Comment by xp4xbox** [comment]
Can you add `print(objSocket.recv(intBuff).decode())` on line 110 and tell me the output.

**Comment by studentnoo** [comment]
> Can you add `print(objSocket.recv(intBuff).decode())` on line 110 in the client and tell me the output.

Same error :(

**Comment by xp4xbox** [comment]
Try the latest commit

**Comment by studentnoo** [comment]
> Try the latest commit

nah bruh that is again showing the same error
![147687261-53783aa6-c590-441e-aeb0-4969cf10a70b](https://user-images.githubusercontent.com/86470814/147695579-821ab11a-8bff-4b29-8263-322aa28b9992.png)

**Comment by studentnoo** [comment]
> Try the latest commit

hey

**Comment by xp4xbox** [comment]
Try thie latest commit, I did a big refactor + improvement
