### ISSUE TITLE
Adding python packages to the client.exe

### ISSUE THREAD

**Issue by RushilKoul** [xp4xbox/Python-Backdoor#81]
OS: Windows 10

I am trying to use `pynput` with the client to simulate keyboard user input through the remote python interpreter. 
However, installing the package using the remote CMD and then using the python interpreter to import it does not work (It says the package is not installed). I'm assuming the client has some sort of its own environment, so how would i go about installing pynput or just general packages to the client?

**Comment by Y4hL** [comment]
You would have to import it in client.py and then recompile it to client.exe

**Comment by xp4xbox** [comment]
pynput is included in the .exe as a dependency already

> You would have to import it in client.py and then recompile it to client.exe
