### ISSUE TITLE
'Match' keyword causes errors

### ISSUE THREAD

**Issue by Alperencode** [xp4xbox/Python-Backdoor#84]
**OS:** Windows 10
**Commit/Build:** 1f50e71 (Latest)

The issue is in python (my version 3.6.6) 'match' keyword causes syntax errors and programs not work. So I rewrite all conditions that cause errors as 'if-elif' blocks. 
<br>
I'll open a PR to this issue so you can check the files and conditions again.

**Comment by xp4xbox** [comment]
Why are you using an old version of python.

**Comment by Alperencode** [comment]
Is it working on newer versions?

**Comment by Rosee-xx** [comment]
im running python 3.9.12 and it still doesnt work

**Comment by Rosee-xx** [comment]
kali linux

**Comment by xp4xbox** [comment]
just give it time, in a year python 3.10+ will be the norm on most computers. For now you can replace them yourself or install 3.10

**Comment by Alperencode** [comment]
If you say so. But even if it's gonna be the norm if this 'switch-case' thing doesn't affect so much efficiency it's still not necessary to use it and cause errors in older versions but it's your project and your call. You can close the issue and the PR whenever you want.
