### ISSUE TITLE
Issue with execution of main_client file in Windows 10

### ISSUE THREAD

**Issue by utkarshborawake** [xp4xbox/Python-Backdoor#88]
**OS:Windows 10** 
main_client generated in dist directory in Kali Linux is not executing on Windows 10 OS. Even after renaming the file .exe it is giving error while executing in Windows 10 OS 
![image](https://user-images.githubusercontent.com/66323315/179567441-3adfeafa-2dd0-4e89-a6b7-fb254d4cc53e.png)
![image](https://user-images.githubusercontent.com/66323315/179568245-617178d2-35fe-444c-b7d8-aa9198e2353a.png)
![image](https://user-images.githubusercontent.com/66323315/179568480-93374892-4328-470f-a0ac-20377c2c049a.png)

**Comment by xp4xbox** [comment]
Thats cause its not a Windows exe, its a linux executable. you have to build the windows one on a windows computer.

**Comment by utkarshborawake** [comment]
So if I build it on Windows while entering host IP address of Kali I will get connection to Kali machine right?

**Comment by xp4xbox** [comment]
yes

**Comment by utkarshborawake** [comment]
whats the correct syntax to perform Download operation?

**Comment by xp4xbox** [comment]
`d directory` to download directory or `d file`

Then enter the target path and output path.
