### ISSUE TITLE
Download feature

### ISSUE THREAD

**Issue by utkarshborawake** [xp4xbox/Python-Backdoor#89]
whats the correct syntax to perform Download operation?
![image](https://user-images.githubusercontent.com/66323315/179988776-8cbcf41e-b419-451d-98f7-f2e0a7b1b71b.png)

**Comment by xp4xbox** [comment]
d directory to download directory or d file to download file

Then enter the target path and output path.

**Comment by utkarshborawake** [comment]
Can you please mention one example to do so.

**Comment by utkarshborawake** [comment]
Thanks man.
