### ISSUE TITLE
Error during run executable on Ubuntu 18.4

### ISSUE THREAD

**Issue by faizul-nayan** [xp4xbox/Python-Backdoor#91]
**OS:** [Ubuntu 18.4]

while I try to run the executable on my Ubuntu 18.4 machine I get error like this

`[31279] Error loading Python lib '/tmp/_MEI9bHivO/libpython3.10.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEI9bHivO/libpython3.10.so.1.0)`

here my ldd version is 2.7

![Screenshot from 2022-12-12 13-49-29](https://user-images.githubusercontent.com/14185985/206990288-b0472561-634c-4d83-835c-fe643ffe942a.png)

however it run perfectly on Mint 21 where ldd version is 2.35

![Screenshot from 2022-12-12 13-56-50](https://user-images.githubusercontent.com/14185985/206991601-2210334a-a7d6-4a7a-ba8b-fcc856f46c75.png)

now ldd 2.35 not supported on Ubuntu 18.4, it's require Ubuntu 20.x for ldd 2.35 or higher

**### can anybody please help me to solve this problem on Ubuntu 18.4?**

**Comment by xp4xbox** [comment]
Interesting, I encountered problems like this all the time and you just gotta try and find a solution through pyinstaller help. There is usually nothing I can do.
