### ISSUE TITLE
setup.py not working

### ISSUE THREAD

**Issue by thegamerchris444** [xp4xbox/Python-Backdoor#93]
**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

 When running the setup.py I get an error C:\Users\total\Downloads\Python-Backdoor-master\Python-Backdoor-master>C:\Users\total\Downloads\Python-Backdoor-master\Python-Backdoor-master\src\setup.py
Traceback (most recent call last):
  File "C:\Users\total\Downloads\Python-Backdoor-master\Python-Backdoor-master\src\setup.py", line 34, in <module>
    from lazagne.config.manage_modules import get_modules_names as lazagne_get_modules_names
ModuleNotFoundError: No module named 'lazagne'

**Comment by winterrdog** [comment]
Try to look [here](https://github.com/AlessandroZ/LaZagne) in order to install lazagne

The error is due to the absence of lazagne on the host system

**Comment by xp4xbox** [comment]
did you make sure to download the submodules and install their requirements?
