### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Sorzus-michael** [xp4xbox/Python-Backdoor#97]
how do i use pyinstaller on this

**Comment by xp4xbox** [comment]
Follow the readme instructions.

**Comment by Sorzus-michael** [comment]
but im on linux  trying to make a .exe.

**Comment by xp4xbox** [comment]
You cant make an .exe on linux, only a linux exec. You have to build it on windows.

**Comment by Sorzus-michael** [comment]
i also get this error: ImportError: No module named _bootlocale

**Comment by xp4xbox** [comment]
I could probably fix `Failed to extract msvcr100.dll\msvcr100.dll: failed to open target file! fopen: No such file or directory)`
