### ISSUE TITLE
[ENHANCEMENT] Easier way to add commands

### ISSUE THREAD

**Issue by Devcom439** [xp4xbox/Python-Backdoor#99]
There should be an easier way of adding commands to either the `server menu` or the `interactive menu`. I'm testing this project and I wanted to add a `shutdown` feature like in cmd. Yet when I looked at all the places where I have to change and add things, it gets too complicated for me. There is just too much work involved for 'just' adding a new command. If you still want to work on this project, I would really appreciate it!

**Comment by xp4xbox** [comment]
It is very organized, you just need to spend some time looking at how its integrated.
